version: "2"

services:
  php-fpm-essential:
    build: './.docker/php'
    container_name: php-fpm-essential
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "${DOCKER_PORT_PHP}:9000"

  nginx-pulsar:
    image: nginx:1-alpine
    container_name: nginx-essential
    links:
      - php-fpm-essential
    depends_on:
      - php-fpm-essential
    ports:
      - "${DOCKER_PORT_NGINX}:80"
    volumes:
      - ./:/app
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
